# Generated by Django 3.2.5 on 2021-07-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_books_posterurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='posterUrl',
            field=models.TextField(max_length=1000),
        ),
    ]
